version: "2"

run:
  timeout: 5m

linters:
  default: none
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - bodyclose
    - gosec
    - noctx
    - sqlclosecheck
    - unconvert
    - unparam
    - wastedassign
    - misspell
    - revive
  settings:
    gosec:
      excludes:
        - G104  # Unhandled errors (too noisy for http.Error calls)
        - G117  # Struct field matching secret pattern (false positive on API key input fields)
    revive:
      rules:
        - name: exported
          severity: warning
          arguments:
            - disableStutteringCheck
        - name: unexported-return
          severity: warning
    misspell:
      locale: US
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - gosec
          - errcheck

formatters:
  enable:
    - gofmt
    - goimports
