run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - bodyclose
    - gosec
    - noctx
    - sqlclosecheck
    - unconvert
    - unparam
    - wastedassign
    - misspell
    - revive
    - gofmt
    - goimports

linters-settings:
  gosec:
    excludes:
      - G104  # Unhandled errors (too noisy for http.Error calls)
  revive:
    rules:
      - name: exported
        severity: warning
      - name: unexported-return
        severity: warning
  misspell:
    locale: US

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
        - errcheck
