version: 2

before:
  hooks:
    - go install github.com/a-h/templ/cmd/templ@latest
    - templ generate
    - >-
      sh -c 'curl -sL
      https://github.com/tailwindlabs/tailwindcss/releases/download/v4.2.0/tailwindcss-linux-x64
      -o /tmp/tailwindcss && chmod +x /tmp/tailwindcss &&
      /tmp/tailwindcss -i web/static/css/input.css -o web/static/css/styles.css --minify'

builds:
  - id: stillwater
    main: ./cmd/stillwater
    binary: stillwater
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
      - -X github.com/sydlexius/stillwater/internal/version.Version={{ .Version }}
      - -X github.com/sydlexius/stillwater/internal/version.Commit={{ .ShortCommit }}
      - -X github.com/sydlexius/stillwater/internal/version.Date={{ .Date }}

archives:
  - id: default
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

dockers:
  - id: amd64
    goos: linux
    goarch: amd64
    image_templates:
      - "ghcr.io/sydlexius/stillwater:{{ .Version }}-amd64"
    dockerfile: build/docker/Dockerfile.goreleaser
    use: buildx
    build_flag_templates:
      - "--platform=linux/amd64"
    extra_files:
      - web/static
      - build/docker/entrypoint.sh

  - id: arm64
    goos: linux
    goarch: arm64
    image_templates:
      - "ghcr.io/sydlexius/stillwater:{{ .Version }}-arm64"
    dockerfile: build/docker/Dockerfile.goreleaser
    use: buildx
    build_flag_templates:
      - "--platform=linux/arm64"
    extra_files:
      - web/static
      - build/docker/entrypoint.sh

docker_manifests:
  - name_template: "ghcr.io/sydlexius/stillwater:{{ .Version }}"
    image_templates:
      - "ghcr.io/sydlexius/stillwater:{{ .Version }}-amd64"
      - "ghcr.io/sydlexius/stillwater:{{ .Version }}-arm64"

  - name_template: "ghcr.io/sydlexius/stillwater:{{ .Major }}.{{ .Minor }}"
    skip_push: "{{ .Prerelease }}"
    image_templates:
      - "ghcr.io/sydlexius/stillwater:{{ .Version }}-amd64"
      - "ghcr.io/sydlexius/stillwater:{{ .Version }}-arm64"

  - name_template: "ghcr.io/sydlexius/stillwater:latest"
    skip_push: "{{ .Prerelease }}"
    image_templates:
      - "ghcr.io/sydlexius/stillwater:{{ .Version }}-amd64"
      - "ghcr.io/sydlexius/stillwater:{{ .Version }}-arm64"

changelog:
  sort: asc
  use: github
  groups:
    - title: Features
      regexp: '^feat(\(.+\))?:'
      order: 0
    - title: Bug Fixes
      regexp: '^fix(\(.+\))?:'
      order: 1
    - title: Performance
      regexp: '^perf(\(.+\))?:'
      order: 2
    - title: Refactoring
      regexp: '^refactor(\(.+\))?:'
      order: 3
    - title: Other
      order: 999
  filters:
    exclude:
      - '^chore:'
      - '^docs:'
      - '^ci:'
      - '^style:'
      - '^test:'
      - Merge pull request
      - Merge branch

release:
  github:
    owner: sydlexius
    name: stillwater
  prerelease: auto
  make_latest: auto
