services:
  emby:
    image: emby/embyserver:latest
    container_name: emby
    ports:
      - "8096:8096"
      - "8920:8920"
    volumes:
      - "~/appdata/emby/config:/config"
      - "~/media/music:/music"
      - "~/media/classical:/classical"
    environment:
      - UID=501
      - GID=20
      - TZ=America/Los_Angeles
    restart: unless-stopped

  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    ports:
      - "8097:8096/tcp"
      - "7359:7359/udp"
    volumes:
      - "~/appdata/jellyfin/config:/config"
      - "~/appdata/jellyfin/cache:/cache"
      - "~/media/music:/music"
      - "~/media/classical:/classical"
    environment:
      - JELLYFIN_PublishedServerUrl=http://localhost:8097
    restart: unless-stopped

  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    ports:
      - "8686:8686"
    volumes:
      - "~/appdata/lidarr:/config"
      - "~/media/music:/music"
      - "~/media/classical:/classical"
    environment:
      - PUID=501
      - PGID=20
      - TZ=America/Los_Angeles
    restart: unless-stopped
