// Command gen-platform-profiles parses the platform_profiles INSERT block in
// internal/database/migrations/001_initial_schema.sql and writes a Markdown
// table to docs/_generated/platform-profiles.md.
//
// The generated file is included verbatim by
// docs/site/src/core-concepts/platform-profiles.md via a pymdownx.snippets
// --8<-- directive, so the hand-written table is replaced by updating the SQL
// seed and re-running the generator.
//
// Usage:
//
//	go run ./cmd/gen-platform-profiles              # rewrite the file in place
//	go run ./cmd/gen-platform-profiles -check       # exit non-zero if regen needed
//	go run ./cmd/gen-platform-profiles -output FILE # write to a different file
//	go run ./cmd/gen-platform-profiles -source FILE # read from a different source
package main

import (
	"bufio"
	"bytes"
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/sydlexius/stillwater/internal/filesystem"
)

// defaultSourcePath is the SQL migration file that contains the
// platform_profiles INSERT block. It is a repo-relative path resolved from
// the current working directory.
const defaultSourcePath = "internal/database/migrations/001_initial_schema.sql"

// defaultOutputPath is the generated Markdown file consumed by the
// --8<-- snippet include in docs/site/src/core-concepts/platform-profiles.md.
const defaultOutputPath = "docs/_generated/platform-profiles.md"

// fileHeader is prepended to every emitted file so contributors know
// not to edit it manually. It uses an HTML comment so it does not
// render as visible text in the docs site.
const fileHeader = "<!-- Generated by gen-platform-profiles. DO NOT EDIT. Run 'make generate-docs' to regenerate. -->\n\n"

func main() {
	var (
		checkOnly  bool
		outPath    string
		sourcePath string
	)
	flag.BoolVar(&checkOnly, "check", false, "exit non-zero if the platform-profiles file needs to be regenerated")
	flag.StringVar(&outPath, "output", defaultOutputPath, "path to the generated Markdown file to write")
	flag.StringVar(&sourcePath, "source", defaultSourcePath, "path to the SQL migration file containing the platform_profiles INSERT block")
	flag.Parse()

	if err := run(sourcePath, outPath, checkOnly); err != nil {
		fmt.Fprintln(os.Stderr, "gen-platform-profiles:", err)
		os.Exit(1)
	}
}

func run(sourcePath, outPath string, checkOnly bool) error {
	// sourcePath and outPath come from flags; this is a developer-only
	// build-time tool so configurable paths are intended.
	src, err := os.ReadFile(sourcePath) //nolint:gosec // G304: developer CLI, path is intentionally configurable
	if err != nil {
		return fmt.Errorf("read %s: %w", sourcePath, err)
	}

	profiles, err := parseProfiles(src)
	if err != nil {
		return fmt.Errorf("parse platform profiles from %s: %w", sourcePath, err)
	}

	rendered := renderTable(profiles)

	// If the output file does not exist yet, treat its contents as empty so
	// the first run (check or write) behaves predictably.
	var existing []byte
	switch raw, rerr := os.ReadFile(outPath); { //nolint:gosec // G304: developer CLI
	case rerr == nil:
		existing = raw
	case os.IsNotExist(rerr):
		existing = nil
	default:
		return fmt.Errorf("read %s: %w", outPath, rerr)
	}

	updated := []byte(fileHeader + rendered)

	if checkOnly {
		if !bytes.Equal(existing, updated) {
			return fmt.Errorf("%s is stale; run `make generate-docs` to regenerate", filepath.ToSlash(outPath))
		}
		return nil
	}

	if bytes.Equal(existing, updated) {
		// Already up to date; skip the write so the file mtime is stable.
		return nil
	}

	// Ensure the output directory exists (docs/_generated/ may not exist in a
	// fresh checkout that has never run generate-docs).
	if err := os.MkdirAll(filepath.Dir(outPath), 0o750); err != nil {
		return fmt.Errorf("create output directory: %w", err)
	}

	if err := filesystem.WriteFileAtomic(outPath, updated, 0o644); err != nil {
		return fmt.Errorf("write %s: %w", outPath, err)
	}
	return nil
}

// profileRow holds the parsed data for one platform profile seed row.
type profileRow struct {
	// ID is the profile's slug (e.g., "emby").
	ID string
	// Name is the display name (e.g., "Emby").
	Name string
	// NFOEnabled is true when nfo_enabled == 1 in the seed.
	NFOEnabled bool
	// ImageNaming maps image slot names (thumb, fanart, logo, banner) to
	// the list of filenames used by this profile.
	ImageNaming map[string][]string
}

// parseProfiles reads the SQL source bytes and extracts profile rows from the
// platform_profiles INSERT block.
//
// The parser scans lines until it finds the INSERT header (a line containing
// "INSERT" and "platform_profiles" and "VALUES"), then reads each subsequent
// row line (a line containing a tuple starting with "('" and ending with "),"
// or ");"). From each tuple it extracts:
//   - the first single-quoted field (id)
//   - the second single-quoted field (name)
//   - the fifth comma-separated value (nfo_enabled, an integer 0 or 1)
//   - the last single-quoted field (image_naming, a JSON object)
//
// The function fails if zero rows parse, so a SQL format change is caught
// rather than silently emitting an empty table.
func parseProfiles(src []byte) ([]profileRow, error) {
	scanner := bufio.NewScanner(bytes.NewReader(src))

	var (
		inBlock  bool
		profiles []profileRow
	)

	for scanner.Scan() {
		line := scanner.Text()
		trimmed := strings.TrimSpace(line)

		// Detect the start of the platform_profiles INSERT block.
		if !inBlock {
			if strings.Contains(trimmed, "INSERT") &&
				strings.Contains(trimmed, "platform_profiles") &&
				strings.Contains(trimmed, "VALUES") {
				inBlock = true
			}
			continue
		}

		// A row tuple: must start with `('` (after trimming leading whitespace).
		if !strings.HasPrefix(trimmed, "('") {
			// The block ended (blank line, comment, next statement, etc.).
			if len(profiles) > 0 {
				break
			}
			continue
		}

		row, err := parseTupleLine(trimmed)
		if err != nil {
			return nil, fmt.Errorf("parse row %q: %w", trimmed, err)
		}
		profiles = append(profiles, row)

		// A row ending with ';' terminates the INSERT statement.
		if strings.HasSuffix(trimmed, ");") {
			break
		}
	}

	if err := scanner.Err(); err != nil {
		return nil, fmt.Errorf("scan source: %w", err)
	}

	if len(profiles) == 0 {
		return nil, fmt.Errorf("no platform_profiles rows found in the SQL source; the INSERT block may be missing or malformed")
	}

	return profiles, nil
}

// parseTupleLine parses a single row line from the platform_profiles INSERT.
//
// Expected shape (leading/trailing whitespace already stripped):
//
//	('emby', 'Emby', 1, 0, 1, 'kodi', '{"thumb":["folder.jpg"],...}'),
//
// The function extracts:
//   - field 0 (id): first single-quoted string
//   - field 1 (name): second single-quoted string
//   - field 4 (nfo_enabled): fifth comma-separated token (integer 0 or 1)
//   - last single-quoted string (image_naming JSON)
func parseTupleLine(line string) (profileRow, error) {
	// Strip the surrounding parentheses and trailing comma/semicolon.
	// Input: ('emby', 'Emby', 1, 0, 1, 'kodi', '...'),
	inner := line
	// Remove leading '('
	inner = strings.TrimPrefix(inner, "(")
	// Remove trailing '),' or ');'
	inner = strings.TrimRight(inner, ",;")
	inner = strings.TrimSuffix(inner, ")")

	// Extract all single-quoted string values and their positions in the
	// original token list so we can also grab integer fields by position.
	quoted := extractQuotedStrings(inner)
	if len(quoted) < 3 {
		return profileRow{}, fmt.Errorf("expected at least 3 quoted string fields, got %d", len(quoted))
	}

	id := quoted[0]
	name := quoted[1]
	imageNamingJSON := quoted[len(quoted)-1] // last quoted field is always image_naming

	// Extract the integer fields by splitting on commas outside of quotes.
	// We need position 4 (0-based) for nfo_enabled.
	tokens, err := splitOutsideQuotes(inner)
	if err != nil {
		return profileRow{}, fmt.Errorf("split tokens: %w", err)
	}
	if len(tokens) < 5 {
		return profileRow{}, fmt.Errorf("expected at least 5 fields, got %d", len(tokens))
	}
	nfoToken := strings.TrimSpace(tokens[4])
	nfoEnabled := nfoToken == "1"

	var naming map[string][]string
	if err := json.Unmarshal([]byte(imageNamingJSON), &naming); err != nil {
		return profileRow{}, fmt.Errorf("unmarshal image_naming JSON %q: %w", imageNamingJSON, err)
	}

	return profileRow{
		ID:          id,
		Name:        name,
		NFOEnabled:  nfoEnabled,
		ImageNaming: naming,
	}, nil
}

// extractQuotedStrings returns the content of each single-quoted string in s,
// in order. Escaped single quotes (”) are treated as a literal single quote
// in the value (standard SQL escaping).
func extractQuotedStrings(s string) []string {
	var results []string
	i := 0
	for i < len(s) {
		if s[i] != '\'' {
			i++
			continue
		}
		// Start of a quoted string.
		i++ // skip opening quote
		var buf strings.Builder
		for i < len(s) {
			if s[i] == '\'' {
				// Check for escaped quote ('').
				if i+1 < len(s) && s[i+1] == '\'' {
					buf.WriteByte('\'')
					i += 2
					continue
				}
				// Closing quote.
				i++
				break
			}
			buf.WriteByte(s[i])
			i++
		}
		results = append(results, buf.String())
	}
	return results
}

// splitOutsideQuotes splits s on commas that are not inside single-quoted
// strings. This handles the image_naming JSON value which itself contains
// commas.
func splitOutsideQuotes(s string) ([]string, error) {
	var (
		tokens  []string
		current strings.Builder
		inQuote bool
	)
	for i := 0; i < len(s); i++ {
		ch := s[i]
		if ch == '\'' {
			if inQuote {
				// Check for escaped quote ('').
				if i+1 < len(s) && s[i+1] == '\'' {
					current.WriteByte('\'')
					i++
					continue
				}
				inQuote = false
			} else {
				inQuote = true
			}
			current.WriteByte(ch)
			continue
		}
		if ch == ',' && !inQuote {
			tokens = append(tokens, current.String())
			current.Reset()
			continue
		}
		current.WriteByte(ch)
	}
	if inQuote {
		return nil, fmt.Errorf("unterminated single-quoted string in row")
	}
	tokens = append(tokens, current.String())
	return tokens, nil
}

// renderTable converts the parsed profile rows into a Markdown table.
//
// Columns: Profile | Thumbnail | Fanart | Logo | Banner | NFO files
// Image cells: each filename wrapped in backticks, joined with ", "; "-" if
// the slot is absent or empty. NFO files: "Yes" or "No".
func renderTable(profiles []profileRow) string {
	var b strings.Builder

	b.WriteString("| Profile | Thumbnail | Fanart | Logo | Banner | NFO files |\n")
	b.WriteString("|---|---|---|---|---|---|\n")

	for _, p := range profiles {
		thumb := imageCell(p.ImageNaming["thumb"])
		fanart := imageCell(p.ImageNaming["fanart"])
		logo := imageCell(p.ImageNaming["logo"])
		banner := imageCell(p.ImageNaming["banner"])
		nfo := "No"
		if p.NFOEnabled {
			nfo = "Yes"
		}
		fmt.Fprintf(&b, "| %s | %s | %s | %s | %s | %s |\n",
			p.Name, thumb, fanart, logo, banner, nfo)
	}

	return b.String()
}

// imageCell formats a list of image filenames as a Markdown table cell value.
// Each filename is wrapped in backticks; multiple filenames are joined with
// ", ". An empty list renders as "-".
func imageCell(names []string) string {
	if len(names) == 0 {
		return "-"
	}
	parts := make([]string, len(names))
	for i, n := range names {
		parts[i] = "`" + n + "`"
	}
	return strings.Join(parts, ", ")
}
