// Command gen-envelope-changelog extracts the envelope-version history from
// the doc-comment on const CurrentEnvelopeVersion in
// internal/settingsio/export.go and writes it as a Markdown bulleted list to
// docs/_generated/envelope-versions.md.
//
// The generated file is included verbatim by docs/architecture-decisions.md
// via a pymdownx.snippets --8<-- directive, so hand-editing that list is
// replaced by updating the source doc-comment and re-running the generator.
//
// Usage:
//
//	go run ./cmd/gen-envelope-changelog              # rewrite the file in place
//	go run ./cmd/gen-envelope-changelog -check       # exit non-zero if regen needed
//	go run ./cmd/gen-envelope-changelog -output FILE # write to a different file
//	go run ./cmd/gen-envelope-changelog -source FILE # read from a different source
package main

import (
	"bufio"
	"bytes"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/sydlexius/stillwater/internal/filesystem"
)

// defaultSourcePath is the Go source file that contains the
// CurrentEnvelopeVersion const with its version-history doc-comment.
// It is a repo-relative path resolved from the current working directory.
const defaultSourcePath = "internal/settingsio/export.go"

// defaultOutputPath is the generated Markdown file consumed by the
// --8<-- snippet include in docs/architecture-decisions.md.
const defaultOutputPath = "docs/_generated/envelope-versions.md"

// fileHeader is prepended to every emitted file so contributors know
// not to edit it manually. It uses an HTML comment so it does not
// render as visible text in the docs site.
const fileHeader = "<!-- Generated by gen-envelope-changelog. DO NOT EDIT. Run 'make generate-docs' to regenerate. -->\n\n"

func main() {
	var (
		checkOnly  bool
		outPath    string
		sourcePath string
	)
	flag.BoolVar(&checkOnly, "check", false, "exit non-zero if the envelope-versions file needs to be regenerated")
	flag.StringVar(&outPath, "output", defaultOutputPath, "path to the generated Markdown file to write")
	flag.StringVar(&sourcePath, "source", defaultSourcePath, "path to the Go source file containing CurrentEnvelopeVersion")
	flag.Parse()

	if err := run(sourcePath, outPath, checkOnly); err != nil {
		fmt.Fprintln(os.Stderr, "gen-envelope-changelog:", err)
		os.Exit(1)
	}
}

func run(sourcePath, outPath string, checkOnly bool) error {
	// sourcePath and outPath come from flags; this is a developer-only
	// build-time tool so configurable paths are intended.
	src, err := os.ReadFile(sourcePath) //nolint:gosec // G304: developer CLI, path is intentionally configurable
	if err != nil {
		return fmt.Errorf("read %s: %w", sourcePath, err)
	}

	entries, err := parseVersionEntries(src)
	if err != nil {
		return fmt.Errorf("parse version entries from %s: %w", sourcePath, err)
	}

	rendered := renderList(entries)

	// If the output file does not exist yet, treat its contents as empty so
	// the first run (check or write) behaves predictably.
	var existing []byte
	switch raw, rerr := os.ReadFile(outPath); { //nolint:gosec // G304: developer CLI
	case rerr == nil:
		existing = raw
	case os.IsNotExist(rerr):
		existing = nil
	default:
		return fmt.Errorf("read %s: %w", outPath, rerr)
	}

	updated := []byte(fileHeader + rendered)

	if checkOnly {
		if !bytes.Equal(existing, updated) {
			return fmt.Errorf("%s is stale; run `make generate-docs` to regenerate", filepath.ToSlash(outPath))
		}
		return nil
	}

	if bytes.Equal(existing, updated) {
		// Already up to date; skip the write so the file mtime is stable.
		return nil
	}

	// Ensure the output directory exists (docs/_generated/ may not exist in a
	// fresh checkout that has never run generate-docs).
	if err := os.MkdirAll(filepath.Dir(outPath), 0o750); err != nil {
		return fmt.Errorf("create output directory: %w", err)
	}

	if err := filesystem.WriteFileAtomic(outPath, updated, 0o644); err != nil {
		return fmt.Errorf("write %s: %w", outPath, err)
	}
	return nil
}

// versionEntry holds one parsed envelope-version line.
type versionEntry struct {
	// Version is the quoted version string, e.g. "1.0".
	Version string
	// Description is the prose after the colon, trimmed of leading whitespace.
	Description string
}

// parseVersionEntries reads the Go source bytes and extracts the bullet-list
// entries from the doc-comment on const CurrentEnvelopeVersion.
//
// Expected comment shape (any line-continuation indentation is accepted):
//
//	//   - "X.Y": some description text
//	//     possibly continued on the next line(s)
//
// A line that starts a new bullet resets the accumulator. Lines that start
// with `//` but do not match a new bullet are treated as continuations and
// appended to the current entry's description.
//
// The function fails if no entries are found so that a malformed or empty
// comment is caught at generation time rather than silently emitting an
// empty file.
func parseVersionEntries(src []byte) ([]versionEntry, error) {
	// Locate the const CurrentEnvelopeVersion declaration so we know where
	// the doc-comment ends.
	const constMarker = `const CurrentEnvelopeVersion`
	constIdx := bytes.Index(src, []byte(constMarker))
	if constIdx < 0 {
		return nil, fmt.Errorf("const CurrentEnvelopeVersion not found in source")
	}

	// Walk backwards from the const declaration, line by line, collecting the
	// contiguous block of // comment lines that immediately precede it.
	before := src[:constIdx]
	lines, err := splitLines(before)
	if err != nil {
		return nil, err
	}

	// Gather the comment block that directly precedes the const (ignoring any
	// trailing blank lines between the last comment and the const keyword).
	var commentBlock []string
	for i := len(lines) - 1; i >= 0; i-- {
		line := strings.TrimSpace(lines[i])
		if line == "" {
			// A single blank line between the comment and const is acceptable;
			// stop if we have already started collecting or encounter a second blank.
			if len(commentBlock) > 0 {
				break
			}
			continue
		}
		if !strings.HasPrefix(line, "//") {
			break
		}
		// Prepend so the block stays in top-to-bottom order.
		commentBlock = append([]string{lines[i]}, commentBlock...)
	}

	if len(commentBlock) == 0 {
		return nil, fmt.Errorf("no doc-comment block found before const CurrentEnvelopeVersion")
	}

	// Parse the bullet entries out of the comment block.
	//
	// A bullet starts with a comment line whose content (after stripping the
	// leading "// ") begins with `- "`.
	var (
		entries []versionEntry
		current *versionEntry
	)

	for _, raw := range commentBlock {
		// Strip the Go comment prefix. The indentation after "//" varies (the
		// current source uses "//   - ..." with three leading spaces inside the
		// comment), so we strip "//" and keep one space of normalisation.
		body := stripCommentPrefix(raw)

		// A new bullet item: matches `  - "X.Y": ...` (flexible leading spaces).
		trimmed := strings.TrimLeft(body, " \t")
		if strings.HasPrefix(trimmed, `- "`) {
			// Flush any previous entry.
			if current != nil {
				entries = append(entries, *current)
			}
			// Parse: `- "VERSION": DESCRIPTION`
			rest := trimmed[2:] // strip `- `
			ver, desc, ok := parseBulletLine(rest)
			if !ok {
				// Malformed bullet line; skip rather than fail so
				// non-version bullets in the comment don't break the parser.
				current = nil
				continue
			}
			current = &versionEntry{Version: ver, Description: desc}
			continue
		}

		// Continuation line: if we are inside a bullet and this is a comment
		// line with non-empty content, append it to the current description.
		if current != nil && trimmed != "" && !strings.HasPrefix(trimmed, "//") {
			current.Description += " " + trimmed
		}
	}

	// Flush the last entry.
	if current != nil {
		entries = append(entries, *current)
	}

	if len(entries) == 0 {
		return nil, fmt.Errorf("no version bullet entries found in the doc-comment on const CurrentEnvelopeVersion")
	}
	return entries, nil
}

// parseBulletLine parses a string of the form `"VERSION": DESCRIPTION` and
// returns the version string, description, and true. Returns false if the
// input does not match the expected shape.
//
// Strict validation rules:
//   - must begin with an opening double-quote
//   - must have a closing double-quote
//   - the character immediately after the closing quote must be ':'
//   - the description (after the colon, trimmed of leading whitespace) must be non-empty
func parseBulletLine(s string) (version, description string, ok bool) {
	// Must start with an opening quote.
	if !strings.HasPrefix(s, `"`) {
		return "", "", false
	}
	closeQuote := strings.Index(s[1:], `"`)
	if closeQuote < 0 {
		return "", "", false
	}
	ver := s[1 : 1+closeQuote]
	// The character immediately after the closing quote must be ':'.
	// Anything else (missing colon, trailing space before colon, etc.) is rejected
	// so that malformed bullets are skipped rather than emitting blank entries.
	rest := strings.TrimLeft(s[1+closeQuote+1:], " \t")
	if !strings.HasPrefix(rest, ":") {
		return "", "", false
	}
	rest = strings.TrimLeft(rest[1:], " \t")
	if rest == "" {
		return "", "", false
	}
	return ver, rest, true
}

// stripCommentPrefix removes the leading "//" (and at most one following space)
// from a Go comment line.
func stripCommentPrefix(line string) string {
	s := strings.TrimSpace(line)
	s = strings.TrimPrefix(s, "//")
	// Preserve the remaining indentation (used to distinguish bullets from
	// their continuation lines) but strip exactly one leading space if present
	// so that "// text" becomes " text" not "  text".
	s = strings.TrimPrefix(s, " ")
	return s
}

// splitLines splits a byte slice into lines, preserving the original line
// content without the trailing newline. It surfaces scanner errors (for
// example a line exceeding bufio.Scanner's buffer) rather than silently
// truncating, so a malformed source can never quietly drop version entries.
func splitLines(src []byte) ([]string, error) {
	var lines []string
	scanner := bufio.NewScanner(bytes.NewReader(src))
	for scanner.Scan() {
		lines = append(lines, scanner.Text())
	}
	if err := scanner.Err(); err != nil {
		return nil, fmt.Errorf("scan source: %w", err)
	}
	return lines, nil
}

// renderList converts the parsed version entries into a Markdown bulleted list.
// Each item uses backtick-wrapped version and a colon separator to match the
// surrounding prose style in docs/architecture-decisions.md.
func renderList(entries []versionEntry) string {
	var b strings.Builder
	for _, e := range entries {
		// Format: - `1.0`: description text
		fmt.Fprintf(&b, "- `%s`: %s\n", e.Version, strings.TrimSpace(e.Description))
	}
	return b.String()
}
